fix!: update scripts
Signed-off-by: Guennadi Maximov C <g.maxc.fox@protonmail.com>

diff --git a/scripts/build/build_vim b/scripts/build/build_vim
--- a/scripts/build/build_vim
+++ b/scripts/build/build_vim
@@ -1,27 +1,27 @@
 #!/usr/bin/env bash
 
-OPTIONS=':hvfcF:'
-FORCE=0
-VERBOSE=0
-FORTIFY=0
-CONFIGURE_ONLY=0
+set -o pipefail
+
+OPTIONS=':hfclF:'
 CONFIGURED=0
+CONFIGURE_ONLY=0
+FORCE=0
+FORTIFY=0
+LTO=0
 
+COMPILE_LOG="${HOME}/.cache/vim_compile.log"
 CURR_DIR="$(pwd)"
-
-export CC='gcc' CXX='g++' CFLAGS="-O2 -g -march=native -pipe -D_GNU_SOURCE -DNDEBUG"
-TARGET_PFX="/usr/local"
-DATAROOTDIR="$TARGET_PFX/share"
-MAN_D="$DATAROOTDIR/man"
-INFO_D="$DATAROOTDIR/info"
-DOC_D="$DATAROOTDIR/doc"
 NPROC="$(nproc)"
+TARGET_PFX="/usr/local"
 
-COMPILE_LOG="$HOME/.cache/vim_compile.log"
+export CC='gcc' CXX='g++' CFLAGS="-O2 -g -march=native -pipe -D_GNU_SOURCE -DNDEBUG -D_DEFAULT_SOURCE"
 
-VIMRT="$TARGET_PFX/share/vim/vim91"
-
-MAKECMD="make -j$NPROC -l$(( NPROC + 1 )) VIMRUNTIMEDIR=$VIMRT"
+VIMRT="${TARGET_PFX}/share/vim/vim91"
+DATAROOTDIR="${TARGET_PFX}/share"
+DOC_D="${DATAROOTDIR}/doc"
+INFO_D="${DATAROOTDIR}/info"
+MAN_D="${DATAROOTDIR}/man"
+MAKECMD="make -j${NPROC} -l$((NPROC + 1)) VIMRUNTIMEDIR=${VIMRT}"
 
 error() {
     local TXT=("$@")
@@ -33,10 +33,7 @@ _cmd() {
     [[ $# -eq 0 ]] && return 127
 
     while [[ $# -gt 0 ]]; do
-        if ! command -v "$1" &> /dev/null; then
-            return 1
-        fi
-
+        ! command -v "$1" &> /dev/null && return 1
         shift
     done
 
@@ -45,10 +42,10 @@ _cmd() {
 
 die() {
     local EC=0
-
     local POPPED_D=0
+
     # In case a chdir operation occured
-    while [[ "$(pwd)" == "$HOME/.build/vim/"* ]]; do
+    while [[ "$(pwd)" == "${HOME}/.build/vim/"* ]]; do
         if [[ $POPPED_D -eq 0 ]]; then
             popd &> /dev/null || POPPED_D=1
         else
@@ -70,7 +67,7 @@ die() {
         fi
     fi
 
-    exit "$EC"
+    exit "${EC}"
 }
 
 usage() {
@@ -80,80 +77,51 @@ usage() {
     local TXT=(
         "build_nvim: A boring neovim build script."
         ""
-        "  usage:   build_nvim -h"
-        "           build_nvim [ -v ] [ -f ] [ -c ] [ -F {1,2,3} ]"
+        "  usage:   build_nvim [-h] [-f] [-c] [-l] [-F 1|2|3]"
         ""
-        "     -h                                    Prints this help message (exit code: 0)"
-        "     -f                                    Skip validation for CWD, attempt to build regardless"
-        "     -c                                    Only trigger \`configure\` stage"
-        "     -v                                    Verbose mode"
+        "     -h                       Prints this help message (exit code: 0)"
+        ""
+        ""
+        "     -F 1|2|3                 Sets \`-D_FORTIFY_SOURCE\` level"
+        ""
+        "     -c                       Only trigger \`configure\` stage"
+        ""
+        "     -f                       Skip validation for CWD, attempt to build regardless"
+        ""
+        "     -l                       Enable Link Time Optimization"
         ""
     )
 
-    die "$EC" "${TXT[@]}"
+    die "${EC}" "${TXT[@]}"
 }
 
 if ! _cmd 'yn'; then
     function yn() {
-        local PROMPT=()
-        if [[ $# -eq 0 ]]; then
-            PROMPT=("Continue?")
-        else
-            PROMPT=("$@")
-        fi
+        local PROMPT="Continue?"
+        [[ $# -gt 0 ]] && PROMPT="$1"
 
-        local LIMIT LIN TRIES=3
+        while true; do
+            local ANS
+            read -rp "${PROMPT} [Y/n]: " ANS
 
-        LIMIT=${#PROMPT[@]}
+            case "$ANS" in
+                [Yy] | "") return 0 ;;
+                [Nn]) return 1 ;;
+                *) continue ;;
+            esac
+        done
 
-            LIMIT=$((LIMIT - 1))
-
-            while [[ $TRIES -gt 0 ]]; do
-                for I in $(seq 0 $LIMIT); do
-                    LIN="${PROMPT[I]}"
-
-                    if [[ $I -eq $LIMIT ]]; then
-                        printf "%s[Y/N]: " "$LIN"
-                    else
-                        printf "%s\n" "$LIN"
-                    fi
-                done
-
-                if [[ $TRIES -le 0 ]]; then
-                    error "You exceeded the maximum amount of tries."
-                    return 1
-                fi
-
-                local ANS
-                read -rp "" ANS
-
-                case "$ANS" in
-                    [Yy]|[Yy][Ee][Ss]) return 0 ;;
-                    [Nn]|[Nn][Oo]) return 1 ;;
-                    *) continue ;;
-                esac
-
-                TRIES=$((TRIES - 1))
-            done
-
-            return 1
-        }
+        return 1
+    }
 fi
 
 _pull() {
-    if [[ $FORCE -eq 1 ]]; then
-        echo -n >| "$COMPILE_LOG"
-        return 0
-    fi
+    [[ $FORCE -eq 1 ]] && echo -n >| "${COMPILE_LOG}" && return 0
 
-    if [[ $VERBOSE -eq 0 ]]; then
-        git pull --rebase >| "$COMPILE_LOG" || die 2 "\`git pull --rebase\` failed"
-    else
-        git pull --rebase | tee "$COMPILE_LOG" || die 2 "\`git pull --rebase\` failed"
-    fi
+    git pull --rebase | tee "${COMPILE_LOG}" || die 2 "\`git pull --rebase\` failed"
 
-    if [[ "$(cat "$COMPILE_LOG")" == *"Already up to date"* ]] && [[ $FORCE -eq 0 ]]; then
-        ! yn "Already up to date. Continue?" && die 0
+    if [[ "$(cat "${COMPILE_LOG}")" == *"Already up to date"* ]] && ! yn "Up to date. Continue?"; then
+        die 0
     fi
 
     return 0
@@ -161,37 +129,46 @@ _pull() {
 
 _configure() {
     ./configure \
-        VIMRUNTIMEDIR="$VIMRT" \
-        --datarootdir="$DATAROOTDIR" \
+        --datarootdir="${DATAROOTDIR}" \
+        --disable-arabic \
         --disable-darwin \
         --disable-farsi \
+        --disable-gnome-check \
         --disable-gtk2-check \
+        --disable-gtktest \
+        --disable-motif-check \
         --disable-rightleft \
         --disable-selinux \
-        --docdir="$DOC_D" \
-        --enable-autoservername \
+        --docdir="${DOC_D}" \
         --enable-cscope \
         --enable-fail-if-missing \
         --enable-fontset \
         --enable-gtk3-check \
         --enable-gui='gtk3' \
-        --enable-luainterp='dynamic' \
+        --enable-luainterp=dynamic \
         --enable-multibyte \
-        --enable-perlinterp='dynamic' \
-        --enable-python3interp='dynamic' \
-        --enable-rubyinterp='dynamic' \
-        --enable-tclinterp='dynamic' \
+        --enable-perlinterp=dynamic \
+        --enable-python3interp=dynamic \
+        --enable-rubyinterp=dynamic \
+        --enable-socketserver \
+        --enable-tclinterp=dynamic \
         --enable-terminal \
-        --infodir="$INFO_D" \
-        --mandir="$MAN_D" \
-        --prefix="$TARGET_PFX" \
+        --enable-wayland-focus-steal \
+        --enable-year2038 \
+        --infodir="${INFO_D}" \
+        --mandir="${MAN_D}" \
+        --prefix="${TARGET_PFX}" \
+        --prefix=/usr/local \
         --sysconfdir="/etc" \
-        --with-features='huge' \
+        --with-features=huge \
+        --with-lua-prefix=/usr \
         --with-luajit \
         --with-python3-config-dir="$(python3-config --configdir)" \
+        --with-wayland \
         --without-gnome \
         --without-x \
-        --with-compiledby='DrKJeff16' 2>&1 | tee "$COMPILE_LOG"
+        --with-compiledby='DrKJeff16' \
+        VIMRUNTIMEDIR="${VIMRT}"
 
     CONFIGURED=1
 
@@ -208,54 +185,44 @@ _verify_configured() {
 }
 
 _drop_fortify() {
-    if ! _verify_configured; then
-        die 1 "Is this even configured?"
-    fi
+    ! _verify_configured && die 1 "Is this even configured?"
 
     if [[ "$FORTIFY" =~ ^[1-3]$ ]]; then
         ! sed -i "s/\s-D_FORTIFY_SOURCE=[0-9]/ -D_FORTIFY_SOURCE=${FORTIFY}/g" ./auto/config.mk \
-            && die 6 "_drop_fortify: ERROR when trying to run \`sed\`!"
+            && die 6 "ERROR when trying to run \`sed\`"
 
-        return 0
+    else
+        ! sed -i 's/\s-D_FORTIFY_SOURCE=[0-9]//g' ./auto/config.mk \
+            && die 6 "ERROR when trying to run \`sed\`"
+
     fi
-
-    ! sed -i 's/\s-D_FORTIFY_SOURCE=[0-9]//g' ./auto/config.mk \
-        && die 6 "_drop_fortify: ERROR when trying to run \`sed\`!"
 
     return 0
 }
 
-if ! _cmd 'make' 'git'; then
-    die 127 "Either \`make\` or \`git\` not found in PATH"
-fi
+! _cmd 'make' 'git' && die 127 "Either \`make\` or \`git\` not found in PATH"
 
-if [[ "$(basename "$CURR_DIR")" != "src" ]]; then
-    die 127 "Not in \`src/\` directory"
-fi
+[[ "$(basename "$CURR_DIR")" != "src" ]] && die 127 "Not in \`src/\` directory"
 
-if ! [[ -d ../.git ]]; then
-    die 127 "Not in \`src/\` directory"
-fi
-if ! [[ -x ./configure ]]; then
-    die 127 "No \`./configure\` executable"
-fi
+! [[ -d ../.git ]] && die 127 "Not in \`src/\` directory"
+! [[ -x ./configure ]] && die 127 "No \`./configure\` executable"
 
 while getopts "$OPTIONS" OPTION; do
     case "$OPTION" in
-        h) usage 0 ;;
-        v) VERBOSE=1 ;;
         F) FORTIFY="${OPTARG}" ;;
-        f) FORCE=1 ;;
         c) CONFIGURE_ONLY=1 ;;
-        :) usage 1 ;;
-        ?) usage 1 ;;
+        f) FORCE=1 ;;
+        l) LTO=1 ;;
+        h) usage 0 ;;
         *) usage 1 ;;
     esac
 done
 
+[[ $LTO -eq 1 ]] && CFLAGS+=" -flto"
+
 _pull
 
-eval "$MAKECMD distclean || die 1 \"\`make distclean\` failed\""
+eval "${MAKECMD} distclean" || die 1 \"\`make distclean\` failed\"
 
 _configure
 _drop_fortify
@@ -263,11 +230,12 @@ EC=$?
 
 [[ $CONFIGURE_ONLY -eq 1 ]] && die "$EC"
 
-eval "$MAKECMD" || die 1 "Compilation failed"
-eval "sudo $MAKECMD install"
+eval "${MAKECMD}" || die 1 "Compilation failed"
+eval "sudo ${MAKECMD} install" || die 1 "Installation failed"
 
-eval "$MAKECMD distclean"
-git restore --staged ../.
-git restore ../.
+eval "${MAKECMD} distclean" || die 1
+
+git restore --staged ../. || die 1
+git restore ../. || die 1
 
 die 0
diff --git a/scripts/envc b/scripts/envc
--- a/scripts/envc
+++ b/scripts/envc
@@ -5,7 +5,6 @@ set -o pipefail -o errexit -o noclobber
 OPTIONS=":hvD:c:o:a:"
 
 TARGET_DIR="$HOME/Documents"
-! [[ -d "$TARGET_DIR" ]] && TARGET_DIR="$(pwd)"
 OUTPUT="env"
 EXT=".tar.xz"
 CMD=""
@@ -33,15 +32,13 @@ TARGETS=(
     "$HOME/.bash_profile"
     "$HOME/.bashrc"
     "$HOME/.bin"
-    "$HOME/.build/AUR/clean_xanmod"
     "$HOME/.build/build_alacritty"
+    "$HOME/.build/build_fastfetch"
     "$HOME/.build/build_hyprland"
     "$HOME/.build/build_nvim"
     "$HOME/.build/build_vim"
     "$HOME/.build/shells/build_yash"
-    "$HOME/.build/suckless"
     "$HOME/.cache/crontab"
-    "$HOME/.condarc"
     "$HOME/.config/alacritty"
     "$HOME/.config/bat"
     "$HOME/.config/chadwm"
@@ -72,11 +69,11 @@ TARGETS=(
     "$HOME/.gnupg"
     "$HOME/.gtkrc-2.0"
     "$HOME/.gtkrc-2.0.mine"
+    "$HOME/.icons"
     "$HOME/.inputrc"
     "$HOME/.librewolf/installs.ini"
     "$HOME/.librewolf/librewolf.overrides.cfg"
     "$HOME/.librewolf/profiles.ini"
-    "$HOME/.local/share/applications"
     "$HOME/.local/share/fontconfig"
     "$HOME/.local/share/fonts"
     "$HOME/.local/share/man"
@@ -166,14 +163,12 @@ TARGETS=(
     "/etc/wireplumber"
 )
 
-# Print args to `/dev/stderr`
 error() {
     local TXT=("$@")
     printf "%s\n" "${TXT[@]}" >&2
     return 0
 }
 
-# Print args to `/dev/stdout` IF program runs on verbose mode
 verb_echo() {
     if [[ $VERBOSE -eq 1 ]]; then
         local TXT=("$@")
@@ -183,7 +178,6 @@ verb_echo() {
     return 0
 }
 
-# Print args to `/dev/stderr` IF program runs on verbose mode
 verb_error() {
     if [[ $VERBOSE -eq 1 ]]; then
         local TXT=("$@")
@@ -193,8 +187,6 @@ verb_error() {
     return 0
 }
 
-# Kill the execution. By default it exits with code `1`.
-# Usage: die [[N] [[text] [...]]]
 die() {
     local EC=1
 
@@ -215,25 +207,17 @@ die() {
     exit "$EC"
 }
 
-# Check if ALL the given programs exist in environment
 _cmd() {
     [[ $# -eq 0 ]] && return 127
 
-    local EC=0
-
     while [[ $# -gt 0 ]]; do
-        if ! command -v "$1" &> /dev/null; then
-            EC=1
-            break
-        fi
-
+        ! command -v "$1" &> /dev/null && return 1
         shift
     done
 
-    return "$EC"
+    return 0
 }
 
-# TODO: Write `usage`.
 usage() {
     local TXT=()
     local EC=0
@@ -241,15 +225,17 @@ usage() {
     [[ "$1" =~ ^(0|-?[1-9][0-9]*)$ ]] && EC="$1"
 
     TXT=(
-        "env_compress: A boring user environment backup tool"
+        "envc: A boring user environment backup tool"
         ""
         "        -h                                              Prints this message, exits successfully"
         ""
-        "        -c [t](xz|gz|bz2)|zip|7z|rar                    Selects a compression method. If not a"
-        "                                                        valid one, aborts with error"
         "        -a /path/to/target1[:/path/to/target2[:...]]    Appends new targets in a colon-separated"
         "                                                        format. If any target is invalid it'll be"
         "                                                        ignored"
+        ""
+        "        -c [t](xz|gz|bz2)|zip|7z|rar                    Selects a compression method. If not a"
+        "                                                        valid one, aborts with error"
+        ""
     )
 
     die "$EC" "${TXT[@]}"
@@ -295,7 +281,6 @@ __destroy_dups() {
     done
 
     TARGETS=("${NEW_TGTS[@]}")
-
     return 0
 }
 
@@ -325,13 +310,11 @@ __check_discard() {
     fi
 
     verb_echo "[DEBUG] Adding \`$T\` to targets"
-
     return 0
 }
 
 __has_git() {
     local NEW_TGTS=()
-
     for T in "${TARGETS[@]}"; do
         if [[ -d "$T" ]] && [[ -n "$(find "$T" -type d -regex '^.*/.git/.*$' 2> /dev/null)" ]]; then
             if ! __in_arr "GIT_OVERRIDES" "$(basename "$T")"; then
@@ -348,9 +331,7 @@ __has_git() {
 
 __filter() {
     local ITEMS=()
-
     for T in "${TARGETS[@]}"; do
-        # If target is a symlink
         ! __check_discard "$T" && continue
 
         if [[ -f "$T" ]] || [[ -d "$T" ]]; then
@@ -368,19 +349,18 @@ method_select() {
     [[ $# -eq 0 ]] && die 1
 
     local MTD="$1"
-
     case "$MTD" in
-        [Tt][Xx][Zz]|[Xx][Zz])
+        [Tt][Xx][Zz] | [Xx][Zz])
             ! _cmd 'tar' 'xz' && die 127 "\`xz\` and/or \`tar\` are not installed"
             EXT=".tar.xz"
             CMD="tar cJvf --group=$TARGET_USER --owner=$TARGET_USER"
             ;;
-        [Tt][Gg][Zz]|[Gg][Zz])
+        [Tt][Gg][Zz] | [Gg][Zz])
             ! _cmd 'tar' 'gzip' && die 127 "\`gzip\` and/or \`tar\` are not installed"
             EXT=".tar.gz"
             CMD="tar czvf --group=$TARGET_USER --owner=$TARGET_USER"
             ;;
-        [Tt][Bb][Zz]2|[Bb][Zz]2)
+        [Tt][Bb][Zz]2 | [Bb][Zz]2)
             ! _cmd 'tar' 'bzip2' && die 127 "\`bzip2\` and/or \`tar\` are not installed"
             EXT=".tar.bz2"
             CMD="tar cjvf --group=$TARGET_USER --owner=$TARGET_USER"
@@ -390,7 +370,7 @@ method_select() {
             EXT=".zip"
             CMD="zip -r -9"
             ;;
-        7[Zz]|7[Zz][Ii][Pp]|[Pp]7[Zz][Ii][Pp])
+        7[Zz] | 7[Zz][Ii][Pp] | [Pp]7[Zz][Ii][Pp])
             ! _cmd '7z' && die 127 "\`7z\` and/or \`tar\` are not installed"
             EXT=".7z"
             CMD="7z -mx=9 -mmt a"
@@ -398,19 +378,18 @@ method_select() {
         :) die 2 "Aborting due to missing parameter for \`$MTD\`." ;;
         *) die 127 "Method unavailable" ;;
     esac
+
     CMD+=" ${TARGET_DIR}/${OUTPUT}${EXT}"
+    return 0
 }
 
 # Verify the existance of the `Target Directory"
 __verify_dir() {
     [[ $# -eq 0 ]] && die 127 "[ERROR] No directory to verify!"
+    ! [[ -d "$1" ]] && die 1 "[ERROR] Not a valid directory \`$1\`"
 
-    local ARG="$1"
-    if [[ -d "$ARG" ]]; then
-        TARGET_DIR="$ARG"
-        return 0
-    fi
-    die 1 "[ERROR] Not a valid directory \`$ARG\`"
+    TARGET_DIR="$1"
+    return 0
 }
 
 __append_targets() {
@@ -431,7 +410,10 @@ fi
 
 while getopts "$OPTIONS" OPTION; do
     case "$OPTION" in
-        c) OVERRIDE_METHOD=1 ; NEW_METHOD="$OPTARG" ;;
+        c)
+            NEW_METHOD="$OPTARG"
+            OVERRIDE_METHOD=1
+            ;;
         D) TARGET_DIR="$OPTARG" ;;
         a) APPENDED+=("$OPTARG") ;;
         v) VERBOSE=1 ;;
@@ -453,21 +435,26 @@ fi
 __verify_dir "$TARGET_DIR"
 __filter
 
-TARGET="${TARGET_DIR}/${OUTPUT}${EXT}"
 if [[ $VERBOSE -eq 1 ]]; then
-    rm -fv "$TARGET" || die 1 "\`$TARGET\` couldn't be removed"
-    sudo tar cJvf "$TARGET" "${TARGETS[@]}" --group="$TARGET_USER" --owner="$TARGET_USER" 2> /dev/null \
+    rm -fv "${TARGET_DIR}/${OUTPUT}${EXT}" || die 1 "\`${TARGET_DIR}/${OUTPUT}${EXT}\` couldn't be removed"
+    sudo tar cJvf "${TARGET_DIR}/${OUTPUT}${EXT}" "${TARGETS[@]}" \
+        --group="$TARGET_USER" \
+        --owner="$TARGET_USER" 2> /dev/null \
         || die 1 "[ERROR] Compression failed"
 
 else
-    rm -f "$TARGET" || die 1 "\`$TARGET\` couldn't be removed"
-    sudo tar cJf "$TARGET" "${TARGETS[@]}" --group="$TARGET_USER" --owner="$TARGET_USER" 2> /dev/null \
+    rm -f "${TARGET_DIR}/${OUTPUT}${EXT}" || die 1 "\`${TARGET_DIR}/${OUTPUT}${EXT}\` couldn't be removed"
+    sudo tar cJf "${TARGET_DIR}/${OUTPUT}${EXT}" "${TARGETS[@]}" \
+        --group="$TARGET_USER" \
+        --owner="$TARGET_USER" 2> /dev/null \
         || die 1 "[ERROR] Compression failed"
 
 fi
 
-sudo chown "${TARGET_USER}:${TARGET_USER}" "$TARGET" || die 4 "[ERROR] Permission setting failed"
-[[ $VERBOSE -eq 1 ]] && du -h "$TARGET"
+sudo chown "${TARGET_USER}:${TARGET_USER}" "${TARGET_DIR}/${OUTPUT}${EXT}" \
+    || die 4 "[ERROR] Permission setting failed"
+
+[[ $VERBOSE -eq 1 ]] && du -h "${TARGET_DIR}/${OUTPUT}${EXT}"
 
 die 0
 # vim:ft=bash:ts=4:sts=4:sw=4:et:
